ZK_CFG_PROPERTY_PREFIX = "hbase.zookeeper.property."
ZOOKEEPER_QUORUM = "hbase.zookeeper.quorum"
CLIENT_PORT_STR = "clientPort"
ZOOKEEPER_CLIENT_PORT = ZK_CFG_PROPERTY_PREFIX + CLIENT_PORT_STR
NO_SEQNUM = -1
