# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Authentication.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41uthentication.proto\x12\x02pb\"E\n\x11\x41uthenticationKey\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x02(\x03\x12\x0b\n\x03key\x18\x03 \x02(\x0c\"\xbf\x01\n\x0fTokenIdentifier\x12&\n\x04kind\x18\x01 \x02(\x0e\x32\x18.pb.TokenIdentifier.Kind\x12\x10\n\x08username\x18\x02 \x02(\x0c\x12\x0e\n\x06key_id\x18\x03 \x02(\x05\x12\x12\n\nissue_date\x18\x04 \x01(\x03\x12\x17\n\x0f\x65xpiration_date\x18\x05 \x01(\x03\x12\x17\n\x0fsequence_number\x18\x06 \x01(\x03\"\x1c\n\x04Kind\x12\x14\n\x10HBASE_AUTH_TOKEN\x10\x00\">\n\x05Token\x12\x12\n\nidentifier\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\x0c\x12\x0f\n\x07service\x18\x03 \x01(\x0c\"\x1f\n\x1dGetAuthenticationTokenRequest\":\n\x1eGetAuthenticationTokenResponse\x12\x18\n\x05token\x18\x01 \x01(\x0b\x32\t.pb.Token\"\x0f\n\rWhoAmIRequest\"7\n\x0eWhoAmIResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0b\x61uth_method\x18\x02 \x01(\t2\xa9\x01\n\x15\x41uthenticationService\x12_\n\x16GetAuthenticationToken\x12!.pb.GetAuthenticationTokenRequest\x1a\".pb.GetAuthenticationTokenResponse\x12/\n\x06WhoAmI\x12\x11.pb.WhoAmIRequest\x1a\x12.pb.WhoAmIResponseBJ\n*org.apache.hadoop.hbase.protobuf.generatedB\x14\x41uthenticationProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Authentication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\024AuthenticationProtosH\001\210\001\001\240\001\001'
  _globals['_AUTHENTICATIONKEY']._serialized_start=28
  _globals['_AUTHENTICATIONKEY']._serialized_end=97
  _globals['_TOKENIDENTIFIER']._serialized_start=100
  _globals['_TOKENIDENTIFIER']._serialized_end=291
  _globals['_TOKENIDENTIFIER_KIND']._serialized_start=263
  _globals['_TOKENIDENTIFIER_KIND']._serialized_end=291
  _globals['_TOKEN']._serialized_start=293
  _globals['_TOKEN']._serialized_end=355
  _globals['_GETAUTHENTICATIONTOKENREQUEST']._serialized_start=357
  _globals['_GETAUTHENTICATIONTOKENREQUEST']._serialized_end=388
  _globals['_GETAUTHENTICATIONTOKENRESPONSE']._serialized_start=390
  _globals['_GETAUTHENTICATIONTOKENRESPONSE']._serialized_end=448
  _globals['_WHOAMIREQUEST']._serialized_start=450
  _globals['_WHOAMIREQUEST']._serialized_end=465
  _globals['_WHOAMIRESPONSE']._serialized_start=467
  _globals['_WHOAMIRESPONSE']._serialized_end=522
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=525
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=694
# @@protoc_insertion_point(module_scope)
