# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MultiRowMutation.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Client_pb2 as Client__pb2
import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MultiRowMutation.proto\x12\x02pb\x1a\x0c\x43lient.proto\x1a\x0bHBase.proto\"\"\n MultiRowMutationProcessorRequest\"#\n!MultiRowMutationProcessorResponse\"\xab\x01\n\x11MutateRowsRequest\x12+\n\x10mutation_request\x18\x01 \x03(\x0b\x32\x11.pb.MutationProto\x12\x13\n\x0bnonce_group\x18\x02 \x01(\x04\x12\r\n\x05nonce\x18\x03 \x01(\x04\x12#\n\x06region\x18\x04 \x01(\x0b\x32\x13.pb.RegionSpecifier\x12 \n\tcondition\x18\x05 \x03(\x0b\x32\r.pb.Condition\"\'\n\x12MutateRowsResponse\x12\x11\n\tprocessed\x18\x01 \x01(\x08\x32V\n\x17MultiRowMutationService\x12;\n\nMutateRows\x12\x15.pb.MutateRowsRequest\x1a\x16.pb.MutateRowsResponseBL\n*org.apache.hadoop.hbase.protobuf.generatedB\x16MultiRowMutationProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MultiRowMutation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\026MultiRowMutationProtosH\001\210\001\001\240\001\001'
  _globals['_MULTIROWMUTATIONPROCESSORREQUEST']._serialized_start=57
  _globals['_MULTIROWMUTATIONPROCESSORREQUEST']._serialized_end=91
  _globals['_MULTIROWMUTATIONPROCESSORRESPONSE']._serialized_start=93
  _globals['_MULTIROWMUTATIONPROCESSORRESPONSE']._serialized_end=128
  _globals['_MUTATEROWSREQUEST']._serialized_start=131
  _globals['_MUTATEROWSREQUEST']._serialized_end=302
  _globals['_MUTATEROWSRESPONSE']._serialized_start=304
  _globals['_MUTATEROWSRESPONSE']._serialized_end=343
  _globals['_MULTIROWMUTATIONSERVICE']._serialized_start=345
  _globals['_MULTIROWMUTATIONSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
