# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PingProtocol.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PingProtocol.proto\x12\rhbase.test.pb\"\r\n\x0bPingRequest\"\x1c\n\x0cPingResponse\x12\x0c\n\x04pong\x18\x01 \x02(\t\"\x0e\n\x0c\x43ountRequest\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\"%\n\x15IncrementCountRequest\x12\x0c\n\x04\x64iff\x18\x01 \x02(\x05\"\'\n\x16IncrementCountResponse\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\r\n\x0bNoopRequest\"\x0e\n\x0cNoopResponse2\xf1\x02\n\x0bPingService\x12?\n\x04ping\x12\x1a.hbase.test.pb.PingRequest\x1a\x1b.hbase.test.pb.PingResponse\x12\x42\n\x05\x63ount\x12\x1b.hbase.test.pb.CountRequest\x1a\x1c.hbase.test.pb.CountResponse\x12X\n\tincrement\x12$.hbase.test.pb.IncrementCountRequest\x1a%.hbase.test.pb.IncrementCountResponse\x12\x42\n\x05hello\x12\x1b.hbase.test.pb.HelloRequest\x1a\x1c.hbase.test.pb.HelloResponse\x12?\n\x04noop\x12\x1a.hbase.test.pb.NoopRequest\x1a\x1b.hbase.test.pb.NoopResponseBJ\n6org.apache.hadoop.hbase.coprocessor.protobuf.generatedB\nPingProtos\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PingProtocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n6org.apache.hadoop.hbase.coprocessor.protobuf.generatedB\nPingProtos\210\001\001\240\001\001'
  _globals['_PINGREQUEST']._serialized_start=37
  _globals['_PINGREQUEST']._serialized_end=50
  _globals['_PINGRESPONSE']._serialized_start=52
  _globals['_PINGRESPONSE']._serialized_end=80
  _globals['_COUNTREQUEST']._serialized_start=82
  _globals['_COUNTREQUEST']._serialized_end=96
  _globals['_COUNTRESPONSE']._serialized_start=98
  _globals['_COUNTRESPONSE']._serialized_end=128
  _globals['_INCREMENTCOUNTREQUEST']._serialized_start=130
  _globals['_INCREMENTCOUNTREQUEST']._serialized_end=167
  _globals['_INCREMENTCOUNTRESPONSE']._serialized_start=169
  _globals['_INCREMENTCOUNTRESPONSE']._serialized_end=208
  _globals['_HELLOREQUEST']._serialized_start=210
  _globals['_HELLOREQUEST']._serialized_end=238
  _globals['_HELLORESPONSE']._serialized_start=240
  _globals['_HELLORESPONSE']._serialized_end=273
  _globals['_NOOPREQUEST']._serialized_start=275
  _globals['_NOOPREQUEST']._serialized_end=288
  _globals['_NOOPRESPONSE']._serialized_start=290
  _globals['_NOOPRESPONSE']._serialized_end=304
  _globals['_PINGSERVICE']._serialized_start=307
  _globals['_PINGSERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
