# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RowProcessor.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RowProcessor.proto\x12\x02pb\"\xb1\x01\n\x0eProcessRequest\x12 \n\x18row_processor_class_name\x18\x01 \x02(\t\x12.\n&row_processor_initializer_message_name\x18\x02 \x01(\t\x12)\n!row_processor_initializer_message\x18\x03 \x01(\x0c\x12\x13\n\x0bnonce_group\x18\x04 \x01(\x04\x12\r\n\x05nonce\x18\x05 \x01(\x04\"/\n\x0fProcessResponse\x12\x1c\n\x14row_processor_result\x18\x01 \x02(\x0c\x32I\n\x13RowProcessorService\x12\x32\n\x07Process\x12\x12.pb.ProcessRequest\x1a\x13.pb.ProcessResponseBH\n*org.apache.hadoop.hbase.protobuf.generatedB\x12RowProcessorProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RowProcessor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\022RowProcessorProtosH\001\210\001\001\240\001\001'
  _globals['_PROCESSREQUEST']._serialized_start=27
  _globals['_PROCESSREQUEST']._serialized_end=204
  _globals['_PROCESSRESPONSE']._serialized_start=206
  _globals['_PROCESSRESPONSE']._serialized_end=253
  _globals['_ROWPROCESSORSERVICE']._serialized_start=255
  _globals['_ROWPROCESSORSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
