# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Snapshot.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FS_pb2 as FS__pb2
import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eSnapshot.proto\x12\x02pb\x1a\x08\x46S.proto\x1a\x0bHBase.proto\"\x8c\x01\n\x10SnapshotFileInfo\x12\'\n\x04type\x18\x01 \x02(\x0e\x32\x19.pb.SnapshotFileInfo.Type\x12\r\n\x05hfile\x18\x03 \x01(\t\x12\x12\n\nwal_server\x18\x04 \x01(\t\x12\x10\n\x08wal_name\x18\x05 \x01(\t\"\x1a\n\x04Type\x12\t\n\x05HFILE\x10\x01\x12\x07\n\x03WAL\x10\x02\"\xbb\x02\n\x16SnapshotRegionManifest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12#\n\x0bregion_info\x18\x02 \x02(\x0b\x32\x0e.pb.RegionInfo\x12<\n\x0c\x66\x61mily_files\x18\x03 \x03(\x0b\x32&.pb.SnapshotRegionManifest.FamilyFiles\x1aN\n\tStoreFile\x12\x0c\n\x04name\x18\x01 \x02(\t\x12 \n\treference\x18\x02 \x01(\x0b\x32\r.pb.Reference\x12\x11\n\tfile_size\x18\x03 \x01(\x04\x1a]\n\x0b\x46\x61milyFiles\x12\x13\n\x0b\x66\x61mily_name\x18\x01 \x02(\x0c\x12\x39\n\x0bstore_files\x18\x02 \x03(\x0b\x32$.pb.SnapshotRegionManifest.StoreFile\"s\n\x14SnapshotDataManifest\x12%\n\x0ctable_schema\x18\x01 \x02(\x0b\x32\x0f.pb.TableSchema\x12\x34\n\x10region_manifests\x18\x02 \x03(\x0b\x32\x1a.pb.SnapshotRegionManifestBD\n*org.apache.hadoop.hbase.protobuf.generatedB\x0eSnapshotProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Snapshot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.apache.hadoop.hbase.protobuf.generatedB\016SnapshotProtosH\001\210\001\001\240\001\001'
  _globals['_SNAPSHOTFILEINFO']._serialized_start=46
  _globals['_SNAPSHOTFILEINFO']._serialized_end=186
  _globals['_SNAPSHOTFILEINFO_TYPE']._serialized_start=160
  _globals['_SNAPSHOTFILEINFO_TYPE']._serialized_end=186
  _globals['_SNAPSHOTREGIONMANIFEST']._serialized_start=189
  _globals['_SNAPSHOTREGIONMANIFEST']._serialized_end=504
  _globals['_SNAPSHOTREGIONMANIFEST_STOREFILE']._serialized_start=331
  _globals['_SNAPSHOTREGIONMANIFEST_STOREFILE']._serialized_end=409
  _globals['_SNAPSHOTREGIONMANIFEST_FAMILYFILES']._serialized_start=411
  _globals['_SNAPSHOTREGIONMANIFEST_FAMILYFILES']._serialized_end=504
  _globals['_SNAPSHOTDATAMANIFEST']._serialized_start=506
  _globals['_SNAPSHOTDATAMANIFEST']._serialized_end=621
# @@protoc_insertion_point(module_scope)
