# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Cell.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nCell.proto\x12\x02pb\"\x87\x01\n\x04\x43\x65ll\x12\x0b\n\x03row\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\x0c\x12\x11\n\tqualifier\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x1f\n\tcell_type\x18\x05 \x01(\x0e\x32\x0c.pb.CellType\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x0c\n\x04tags\x18\x07 \x01(\x0c\"\x8a\x01\n\x08KeyValue\x12\x0b\n\x03row\x18\x01 \x02(\x0c\x12\x0e\n\x06\x66\x61mily\x18\x02 \x02(\x0c\x12\x11\n\tqualifier\x18\x03 \x02(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x1e\n\x08key_type\x18\x05 \x01(\x0e\x32\x0c.pb.CellType\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x0c\n\x04tags\x18\x07 \x01(\x0c*{\n\x08\x43\x65llType\x12\x0b\n\x07MINIMUM\x10\x00\x12\x07\n\x03PUT\x10\x04\x12\n\n\x06\x44\x45LETE\x10\x08\x12\x19\n\x15\x44\x45LETE_FAMILY_VERSION\x10\n\x12\x11\n\rDELETE_COLUMN\x10\x0c\x12\x11\n\rDELETE_FAMILY\x10\x0e\x12\x0c\n\x07MAXIMUM\x10\xff\x01\x42\x44\n1org.apache.hadoop.hbase.shaded.protobuf.generatedB\nCellProtosH\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Cell_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1org.apache.hadoop.hbase.shaded.protobuf.generatedB\nCellProtosH\001\240\001\001'
  _globals['_CELLTYPE']._serialized_start=297
  _globals['_CELLTYPE']._serialized_end=420
  _globals['_CELL']._serialized_start=19
  _globals['_CELL']._serialized_end=154
  _globals['_KEYVALUE']._serialized_start=157
  _globals['_KEYVALUE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
