# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ZooKeeper.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HBase_pb2 as HBase__pb2
import ClusterStatus_pb2 as ClusterStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fZooKeeper.proto\x12\x02pb\x1a\x0bHBase.proto\x1a\x13\x43lusterStatus.proto\"m\n\x10MetaRegionServer\x12\x1e\n\x06server\x18\x01 \x02(\x0b\x32\x0e.pb.ServerName\x12\x13\n\x0brpc_version\x18\x02 \x01(\r\x12$\n\x05state\x18\x03 \x01(\x0e\x32\x15.pb.RegionState.State\"P\n\x06Master\x12\x1e\n\x06master\x18\x01 \x02(\x0b\x32\x0e.pb.ServerName\x12\x13\n\x0brpc_version\x18\x02 \x01(\r\x12\x11\n\tinfo_port\x18\x03 \x01(\r\"\x1f\n\tClusterUp\x12\x12\n\nstart_date\x18\x01 \x02(\t\"\x9f\x01\n\x0cSplitLogTask\x12%\n\x05state\x18\x01 \x02(\x0e\x32\x16.pb.SplitLogTask.State\x12#\n\x0bserver_name\x18\x02 \x02(\x0b\x32\x0e.pb.ServerName\"C\n\x05State\x12\x0e\n\nUNASSIGNED\x10\x00\x12\t\n\x05OWNED\x10\x01\x12\x0c\n\x08RESIGNED\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x12\x07\n\x03\x45RR\x10\x04\"\x8f\x01\n\x14\x44\x65precatedTableState\x12\x36\n\x05state\x18\x01 \x02(\x0e\x32\x1e.pb.DeprecatedTableState.State:\x07\x45NABLED\"?\n\x05State\x12\x0b\n\x07\x45NABLED\x10\x00\x12\x0c\n\x08\x44ISABLED\x10\x01\x12\r\n\tDISABLING\x10\x02\x12\x0c\n\x08\x45NABLING\x10\x03\"\x1e\n\x0bSwitchState\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x42L\n1org.apache.hadoop.hbase.shaded.protobuf.generatedB\x0fZooKeeperProtosH\x01\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ZooKeeper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1org.apache.hadoop.hbase.shaded.protobuf.generatedB\017ZooKeeperProtosH\001\210\001\001\240\001\001'
  _globals['_METAREGIONSERVER']._serialized_start=57
  _globals['_METAREGIONSERVER']._serialized_end=166
  _globals['_MASTER']._serialized_start=168
  _globals['_MASTER']._serialized_end=248
  _globals['_CLUSTERUP']._serialized_start=250
  _globals['_CLUSTERUP']._serialized_end=281
  _globals['_SPLITLOGTASK']._serialized_start=284
  _globals['_SPLITLOGTASK']._serialized_end=443
  _globals['_SPLITLOGTASK_STATE']._serialized_start=376
  _globals['_SPLITLOGTASK_STATE']._serialized_end=443
  _globals['_DEPRECATEDTABLESTATE']._serialized_start=446
  _globals['_DEPRECATEDTABLESTATE']._serialized_end=589
  _globals['_DEPRECATEDTABLESTATE_STATE']._serialized_start=526
  _globals['_DEPRECATEDTABLESTATE_STATE']._serialized_end=589
  _globals['_SWITCHSTATE']._serialized_start=591
  _globals['_SWITCHSTATE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
